dbt_cloud:
  outputs:
    dev:
      account: LOB14208
      database: analytics
      password: sachin$123
      role: analyticsengineer
      schema: dbt_akchouksey
      threads: 3
      type: snowflake
      user: sachin
      warehouse: transform_wh

  target: dev
