version: 2

sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: regions
      - name: v_nations
      - name: nations
      - name: suppliers
      - name: orders
        config:
          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 2, period: hour}
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts

  - name: mkm
    database: ANALYTICS
    schema: MKMALL
    tables:
      - name: stg_employees
